apiVersion: apps/v1
kind: Deployment
metadata:
  name: juego-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juego
  template:
    metadata:
      labels:
        app: juego
    spec:
      containers:
      - name: juego
        image: juego-multijugador:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
